In [1]:
import pandas as pd

In [2]:
df1 = pd. read_csv ( "datos_ecuestas.csv" )

In [3]:
df1

,Transaccion_Peri�odo,Anios,Anios (2),Anios (2).1,Anios (2).2,Anios (2).3,Anios (2).4,Anios (2).5,Anios (2).6,Trimestres,...,Trimestres.22,Trimestres.23,Trimestres.24,Trimestres.25,Trimestres.26,Trimestres.27,Trimestres.28,Trimestres.29,Trimestres.30,Trimestres.31
0,CUENTA CORRIENTE,2002,2003,2004,2005,2006,2007,2008,2009,2002-I,...,2007-III,2007-IV,2008-I,2008-II,2008-III,2008-IV,2009-I,2009-II,2009-III,2009-IV
1,BIENES,-1271,-422.3,-541.9,287.9,1510.2,1574.6,1002.4,-310.7,-307.4,...,614.9,549,1226.6,1294.4,39,-1566.1,-871.6,69.3,460.6,4.4
2,Exportaciones,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Mercanci�as generales (3),-902,79.5,284,758.3,1768.4,1823,1371.3,75.2,-219.1,...,640.3,585.9,1207.5,1406.3,170.2,-1412.7,-687.9,204.6,394.6,163.9
4,Bienes para transformacion,5257.7,6445.8,7967.8,10467.7,13176.1,14870.2,19146.9,14344.3,1151.6,...,3970,4419.4,4785.3,5669.6,5348.5,3343.5,2784.3,3425.7,3936.9,4197.3
5,Reparacion de bienes,5115.6,6305.6,7831.9,10247.2,12903.9,14556.2,18761.8,14060.2,1122.3,...,3886.1,4325.7,4682.4,5558.8,5242.4,3278.1,2726.2,3361.2,3858.3,4114.4
6,Bienes adquiridos en puerto por medios de tran...,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
7,Oro no monetario,6.5,5.4,5.6,6,6,6,6,6,2,...,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5
8,Mercancias generales_(3)_(4),135.6,134.8,130.3,214.5,266.2,308,379.1,278.1,27.3,...,82.4,92.2,101.3,109.3,104.6,63.9,56.6,63.1,77.1,81.4
9,Bienes para transformacion,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
10,Reparacion de bienes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Bienes adquiridos en puerto por medios de tran...,-6159.7,-6366.3,-7683.7,-9709.4,-11407.7,-13047.1,-17775.5,-14269.1,-1370.7,...,-3329.8,-3833.6,-3577.8,-4263.3,-5178.3,-4756.2,-3472.2,-3221.1,-3542.4,-4033.4
12,Oro no monetario,-6135.2,-6344.2,-7656.6,-9686.6,-11384.9,-13024.3,-17752.7,-14246.3,-1364.2,...,-3324.1,-3827.9,-3572.1,-4257.6,-5172.6,-4750.5,-3466.5,-3215.4,-3536.7,-4027.7
13,SERVICIOS,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
14,Servicios prestados,-6,-5.3,-10.4,-6,-6,-6,-6,-6,-1.5,...,-1.5,-1.5,-1.5,-1.5,-1.5,-1.5,-1.5,-1.5,-1.5,-1.5
15,Transporte,-18.5,-16.8,-16.8,-16.8,-16.8,-16.8,-16.8,-16.8,-5,...,-4.2,-4.2,-4.2,-4.2,-4.2,-4.2,-4.2,-4.2,-4.2,-4.2
16,Viajes,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
17,Otros servicios,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,Servicios recibidos,-715.9,-743.6,-953.7,-1129.9,-1304.7,-1371.5,-1641.3,-1389.8,-169.1,...,-338.1,-372.4,-358.9,-418,-432.3,-432.1,-381.8,-314.8,-310.7,-382.5
19,Transporte,883.9,881.2,1013.9,1012.1,1036.5,1200.1,1313.1,1213.8,211.4,...,316.7,308.1,301,334.3,344.1,333.7,291.7,297.2,315.3,309.6
20,Viajes,243.4,268.6,340.5,335.2,352.2,347.6,365.8,338.3,53.2,...,92.7,91.5,82.7,94.4,98.7,90.1,73.9,84.7,90.6,89.1
21,Otros servicios,447.2,406.4,462.5,485.8,489.9,623.4,741.8,663.4,108,...,168.7,163,165.4,187.5,195.5,193.4,164.3,158.9,173.2,166.9
22,RENTA,193.4,206.2,211,191.2,194.4,229.1,205.5,212,50.1,...,55.3,53.6,52.9,52.4,50,50.2,53.4,53.6,51.5,53.6
23,Renta recibida,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,Remuneracion de empleados,-1599.9,-1624.7,-1967.7,-2142,-2341.3,-2571.6,-2954.4,-2603.6,-380.5,...,-654.8,-680.6,-659.9,-752.3,-776.4,-765.8,-673.4,-612,-626,-692.2
25,Renta de la inversion,-674.8,-667.9,-910.7,-1042.5,-1170.9,-1327,-1634.2,-1366.9,-155.9,...,-348.5,-370.7,-356.2,-388.5,-458.9,-430.6,-347.2,-303.5,-334.5,-381.8
26,Inversion directa,-363.9,-354.4,-391,-428.6,-466.3,-504,-541.6,-548.7,-88,...,-125.9,-127.2,-133,-136.6,-135.3,-136.7,-134.8,-138.4,-137.1,-138.5
27,Inversion de car...,-561.1,-602.5,-666,-670.9,-704.1,-740.6,-778.6,-688,-136.5,...,-180.4,-182.7,-170.7,-227.3,-182.2,-198.5,-191.5,-170.2,-154.4,-171.9
28,Otra inversion,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,Renta pagada,-1304.8,-1527.7,-1902.4,-1941.6,-1950,-2046.9,-1589.8,-1439.1,-293.2,...,-526.4,-522.8,-395.5,-419,-415.4,-368.4,-324.2,-412.6,-301.3,-427.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Activos de reserva (5),-1.7,0.7,0.8,-10.4,-7.5,-8.3,-3.3,799.3,-0.7,...,-2.2,-0.6,-1.9,-,-1.3,-,-1.3,-0.7,920.8,-119.4
93,Oro monetario,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
94,Derechos especiales de giro,-20.8,105.5,341.6,322.2,369.4,523.9,683.7,360.7,-1.9,...,120,116.3,174.4,174.4,158.1,176.7,104.5,80.6,100.2,75.3
95,Posicion de reserva en el FMI,NaN,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,Divisas,1105.2,-54.3,84.8,-382.1,646.9,683.9,-1151.8,199.5,894.4,...,99.2,95.7,-698.1,-256.9,129.3,-326,-65.1,-173.5,506.5,-68.3
97,Otros activos,-141,-47.6,-64.6,-33.9,-0.5,-0.6,-0.6,-0.6,-34.3,...,-0.1,-0.2,-0.1,-0.2,-0.1,-0.2,-0.1,-0.2,-0.1,-0.2
98,ERRORES Y OMISIONES,-13.2,88,-423.1,-572.8,2.3,239.5,-588.1,683.1,-11.3,...,-49.4,144.2,-284.8,-249.7,-21.9,-31.8,-83.1,-10.1,808.6,-32.3
99,ERRORES Y OMISIONES,-26,-26.1,-21,-25.7,-12.9,-7.2,-2.3,-2,-4.1,...,-0.9,-2.7,-1,-0.3,-0.7,-0.3,-0.7,-0.3,-0.7,-0.3
100,ERRORES Y OMISIONES,1285.3,-68.7,593.6,250.2,658,452.1,-560.7,-481,944.1,...,149.6,-45.6,-412.2,-6.8,152,-293.7,18.9,-163,-301.3,-35.6
101,ERRORES Y OMISIONES,NaN,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
102,ERRORES Y OMISIONES,-,46.1,57.9,-58.4,79.2,48.9,65.5,-66.9,-,...,29.5,10.9,39.5,0.6,-1,26.4,-46.4,-31.5,-25.8,36.8
103,ERRORES Y OMISIONES,-,45.3,24.7,-49.2,17.4,23.6,17.3,21.7,-,...,18.4,6.2,15.7,-6.9,-19.8,28.3,-43.2,41.2,-9.5,33.1
104,ERRORES Y OMISIONES,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
105,ERRORES Y OMISIONES,-,0.8,33.2,-9.2,61.8,25.3,48.2,-88.6,-,...,11.2,4.7,23.8,7.5,18.8,-1.9,-3.2,-72.7,-16.3,3.7
106,ERRORES Y OMISIONES,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
107,ERRORES Y OMISIONES,NaN,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
108,ERRORES Y OMISIONES,50.6,-115.5,-11.2,-13.6,-0.5,68.1,-7.1,-6.5,13.7,...,-13.4,56.1,-60.1,-8.2,0.7,60.6,104,5.7,9.7,5.1
109,ERRORES Y OMISIONES,-0.2,0,0,-,0,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
110,ERRORES Y OMISIONES,59.4,-110.3,-11.2,-13.6,-0.5,68.1,-7.1,-6.5,21.1,...,-13.4,56.1,-60.1,-8.2,0.7,61.3,104,5.7,9.7,5.1
111,ERRORES Y OMISIONES,-8.7,-5.1,-,-,-,-,-,-,-8.5,...,-,-,-,-,-,-,-,-,-,-
112,ERRORES Y OMISIONES,0,-0.1,-,-,-,-,-,-,1.2,...,-,-,-,-,-,-0.8,-,-,-,-
113,ERRORES Y OMISIONES,NaN,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
114,ERRORES Y OMISIONES,65.8,-152.4,-276.9,-709.6,123.6,-1497.5,-952.2,681,41.1,...,-406.8,90.3,-622.7,-1959.6,-408.3,2038.4,1229,569.1,-1949.7,832.7
115,ERRORES Y OMISIONES,-59.5,-54.7,-20,-65.4,-100.5,-170.4,-30.4,-183.9,-21.1,...,-78.1,-76.7,-84.3,2.8,38.6,12.5,-39.5,-15.2,-51.7,-77.5
116,ERRORES Y OMISIONES,0.5,1.1,-54.9,34.1,14.2,-16.9,-1.7,-0.5,1.6,...,-23.5,-0.5,-0.7,-2.8,1.4,0.4,0.8,-1,-0.5,0.2
117,ERRORES Y OMISIONES,-1.7,-2.1,-1.2,2,-1.3,-1.3,0.7,-0.5,0.2,...,-0.7,-0.4,-1.1,0.2,1.3,0.3,0.8,-1,-0.6,0.3
118,ERRORES Y OMISIONES,126.2,-94,-195.8,-683.5,212.3,-1307.1,-948.9,865.2,57.1,...,-310.2,167.1,-535.8,-1944.6,-445.6,1977.2,1311.9,547.6,-1881.2,886.9
119,ERRORES Y OMISIONES,0.2,-2.7,-5,3.2,-1.1,-1.7,28.1,0.7,3.3,...,5.7,0.8,-0.8,-15.1,-4.1,48.1,-45,38.6,-15.7,22.8
120,ERRORES Y OMISIONES,NaN,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
121,ERRORES Y OMISIONES,-170.8,153.4,577.3,367.4,333.4,-41.1,247.4,193.4,-18.3,...,31.6,15.2,62.7,33.2,84.6,67,-15.4,92.8,-122,134.8

In [4]:
df1. iloc [ 0 : 3 , 0 : 2 ]

  Transaccion_Peri�odo Anios
0     CUENTA CORRIENTE   2002
1               BIENES  -1271
2       Exportaciones       0

In [5]:
df1. ix [ 0 : 3 , "Anios " : "Trimestres"]

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

,Anios,Anios (2),Anios (2).1,Anios (2).2,Anios (2).3,Anios (2).4,Anios (2).5,Anios (2).6,Trimestres
0,2002,2003,2004,2005,2006,2007,2008,2009,2002-I
1,-1271,-422.3,-541.9,287.9,1510.2,1574.6,1002.4,-310.7,-307.4
2,0,0,0,0,0,0,0,0,0
3,-902,79.5,284,758.3,1768.4,1823,1371.3,75.2,-219.1

In [6]:
df1.head()

,Transaccion_Peri�odo,Anios,Anios (2),Anios (2).1,Anios (2).2,Anios (2).3,Anios (2).4,Anios (2).5,Anios (2).6,Trimestres,...,Trimestres.22,Trimestres.23,Trimestres.24,Trimestres.25,Trimestres.26,Trimestres.27,Trimestres.28,Trimestres.29,Trimestres.30,Trimestres.31
0,CUENTA CORRIENTE,2002,2003,2004,2005,2006,2007,2008,2009,2002-I,...,2007-III,2007-IV,2008-I,2008-II,2008-III,2008-IV,2009-I,2009-II,2009-III,2009-IV
1,BIENES,-1271,-422.3,-541.9,287.9,1510.2,1574.6,1002.4,-310.7,-307.4,...,614.9,549,1226.6,1294.4,39,-1566.1,-871.6,69.3,460.6,4.4
2,Exportaciones,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Mercanci�as generales (3),-902,79.5,284,758.3,1768.4,1823,1371.3,75.2,-219.1,...,640.3,585.9,1207.5,1406.3,170.2,-1412.7,-687.9,204.6,394.6,163.9
4,Bienes para transformacion,5257.7,6445.8,7967.8,10467.7,13176.1,14870.2,19146.9,14344.3,1151.6,...,3970,4419.4,4785.3,5669.6,5348.5,3343.5,2784.3,3425.7,3936.9,4197.3

In [7]:
df1 = df1[1:]

In [8]:
df1.shape

(121, 41)

In [9]:
df1.values

array([['BIENES', '-1271', '-422.3', ..., '69.3', '460.6', '4.4'],
       ['Exportaciones ', '0', '0', ..., '0', '0', '0'],
       ['Mercanci\xadas generales (3)', '-902', '79.5', ..., '204.6',
        '394.6', '163.9'],
       ...,
       ['ERRORES Y OMISIONES', '0.2', '-2.7', ..., '38.6', '-15.7', '22.8'],
       ['ERRORES Y OMISIONES', nan, '0', ..., '0', '0', '0'],
       ['ERRORES Y OMISIONES', '-170.8', '153.4', ..., '92.8', '-122',
        '134.8']], dtype=object)

In [10]:
df1.index

RangeIndex(start=1, stop=122, step=1)

In [11]:
df1.columns

Index([u'Transaccion_Peri�odo', u'Anios ', u'Anios (2)', u'Anios (2).1',
       u'Anios (2).2', u'Anios (2).3', u'Anios (2).4', u'Anios (2).5',
       u'Anios (2).6', u'Trimestres', u'Trimestres.1', u'Trimestres.2',
       u'Trimestres.3', u'Trimestres.4', u'Trimestres.5', u'Trimestres.6',
       u'Trimestres.7', u'Trimestres.8', u'Trimestres.9', u'Trimestres.10',
       u'Trimestres.11', u'Trimestres.12', u'Trimestres.13', u'Trimestres.14',
       u'Trimestres.15', u'Trimestres.16', u'Trimestres.17', u'Trimestres.18',
       u'Trimestres.19', u'Trimestres.20', u'Trimestres.21', u'Trimestres.22',
       u'Trimestres.23', u'Trimestres.24', u'Trimestres.25', u'Trimestres.26',
       u'Trimestres.27', u'Trimestres.28', u'Trimestres.29', u'Trimestres.30',
       u'Trimestres.31'],
      dtype='object')

In [12]:
df2 = df1.set_index('Trimestres')

In [13]:
df2.head()

,Transaccion_Peri�odo,Anios,Anios (2),Anios (2).1,Anios (2).2,Anios (2).3,Anios (2).4,Anios (2).5,Anios (2).6,Trimestres.1,...,Trimestres.22,Trimestres.23,Trimestres.24,Trimestres.25,Trimestres.26,Trimestres.27,Trimestres.28,Trimestres.29,Trimestres.30,Trimestres.31
Trimestres,,,,,,,,,,,,,,,,,,,,,
-307.4,BIENES,-1271,-422.3,-541.9,287.9,1510.2,1574.6,1002.4,-310.7,-423.8,...,614.9,549,1226.6,1294.4,39,-1566.1,-871.6,69.3,460.6,4.4
0,Exportaciones,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-219.1,Mercanci�as generales (3),-902,79.5,284,758.3,1768.4,1823,1371.3,75.2,-314.8,...,640.3,585.9,1207.5,1406.3,170.2,-1412.7,-687.9,204.6,394.6,163.9
1151.6,Bienes para transformacion,5257.7,6445.8,7967.8,10467.7,13176.1,14870.2,19146.9,14344.3,1355.5,...,3970,4419.4,4785.3,5669.6,5348.5,3343.5,2784.3,3425.7,3936.9,4197.3
1122.3,Reparacion de bienes,5115.6,6305.6,7831.9,10247.2,12903.9,14556.2,18761.8,14060.2,1322.9,...,3886.1,4325.7,4682.4,5558.8,5242.4,3278.1,2726.2,3361.2,3858.3,4114.4

In [14]:
datos = df1.drop(['Anios (2)','Anios (2).2','Anios (2).3','Anios (2).4','Anios (2).5','Anios (2).6','Trimestres.1','Trimestres.2','Trimestres.3',
                  'Trimestres.4','Trimestres.5','Trimestres.6','Trimestres.7','Trimestres.8','Trimestres.9',
                  'Trimestres.10','Trimestres.11','Trimestres.12','Trimestres.13','Trimestres.14',
                  'Trimestres.15','Trimestres.16','Trimestres.17','Trimestres.18','Trimestres.19','Trimestres.20','Trimestres.21',
                  'Trimestres.22','Trimestres.23','Trimestres.24','Trimestres.25','Trimestres.26','Trimestres.27','Trimestres.28','Trimestres.29','Trimestres.30'], axis=1)
datos.head()

         Transaccion_Peri�odo  Anios  Anios (2).1 Trimestres Trimestres.31
1                      BIENES   -1271      -541.9     -307.4           4.4
2              Exportaciones        0           0          0             0
3   Mercanci�as generales (3)    -902         284     -219.1         163.9
4  Bienes para transformacion  5257.7      7967.8     1151.6        4197.3
5       Reparacion de bienes   5115.6      7831.9     1122.3        4114.4

In [15]:
datos.columns = ['Transaccion', 'Anios', 'Incidencia','Brecha','Severidad']
datos.head()

                  Transaccion   Anios Incidencia  Brecha Severidad
1                      BIENES   -1271     -541.9  -307.4       4.4
2              Exportaciones        0          0       0         0
3   Mercanci�as generales (3)    -902        284  -219.1     163.9
4  Bienes para transformacion  5257.7     7967.8  1151.6    4197.3
5       Reparacion de bienes   5115.6     7831.9  1122.3    4114.4